# Generated by Django 5.2.4 on 2025-12-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='Данные вебхука')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('amocrm_contact_id', models.IntegerField(blank=True, null=True)),
                ('amocrm_lead_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог вебхука',
                'verbose_name_plural': 'Логи вебхуков',
                'ordering': ['-created_at'],
            },
        ),
    ]
