# Generated by Django 5.2.4 on 2026-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='pipeline',
            field=models.CharField(choices=[('default', 'Основная'), ('klaster', 'Кластер')], default='default', max_length=20, verbose_name='Воронка'),
        ),
    ]
